version: "3.7"

services:

  # PRODUCT
  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8010:8000"
    volumes:
      - ./product-service:/app
    working_dir: /app
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app
      --log-config /app/configs/log_conf.yml
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - product-db
    networks:
      - gen-ia-network

  product-db:
    image: postgres:17
    container_name: product-db
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=product
      - POSTGRES_DB=product-service
    volumes:
      - ./product-service/configs/migrations/:/docker-entrypoint-initdb.d/
      - product_db_vol:/var/lib/postgresql/data
    networks:
      - gen-ia-network

  # WEATHER
  weather-service:
    build:
      context: ./weather-service
    container_name: weather-service
    ports:
      - "8011:8000"
    volumes:
      - ./weather-service:/app
    working_dir: /app
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app
      --log-config /app/configs/log_conf.yml
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - weather-db
    networks:
      - gen-ia-network

  weather-db:
    image: postgres:17
    container_name: weather-db
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=weather
      - POSTGRES_PASSWORD=weather
      - POSTGRES_DB=weather-service
    volumes:
      - ./weather-service/configs/migrations/:/docker-entrypoint-initdb.d/
      - weather_db_vol:/var/lib/postgresql/data
    networks:
      - gen-ia-network

  # ORDER
  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8012:8000"
    volumes:
      - ./order-service:/app
    working_dir: /app
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app
      --log-config /app/configs/log_conf.yml
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - order-db
      - order-llm-ollama
    networks:
      - gen-ia-network

  order-db:
    image: mongo
    container_name: order-db
    ports:
      - "27020:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=order
      - MONGO_INITDB_ROOT_PASSWORD=order
    volumes:
      - order_db_vol:/data/db
    networks:
      - gen-ia-network

  order-cache:
    image: redis
    container_name: order-cache
    ports:
      - "6389:6379"
    networks:
      - gen-ia-network

  order-llm-ollama:
    image: ollama/ollama:latest
    container_name: order-llm-ollama
    ports:
      - "11440:11434"
    environment:
      - OLLAMA_NUM_THREADS=12
    volumes:
      - ollama_vol:/root/.ollama
    networks:
      - gen-ia-network

  # CUSTOMER
  customer-service:
    build:
      context: ./customer-service
    container_name: customer-service
    ports:
      - "8013:8000"
    volumes:
      - ./customer-service:/app
    working_dir: /app
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /app
      --log-config /app/configs/log_conf.yml
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - customer-db
    networks:
      - gen-ia-network

  customer-db:
    image: postgres:17
    container_name: customer-db
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_USER=customer
      - POSTGRES_PASSWORD=customer
      - POSTGRES_DB=customer-service
    volumes:
      - ./customer-service/configs/migrations/:/docker-entrypoint-initdb.d/
      - customer_db_vol:/var/lib/postgresql/data
    networks:
      - gen-ia-network

volumes:
  product_db_vol: {}
  customer_db_vol: {}
  weather_db_vol: {}
  order_db_vol: {}
  ollama_vol: {}

networks:
  gen-ia-network:
    driver: bridge
  
